config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index"
  # get "/signup" => "users#new"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  resources :users
  # resources :accounts
  resources :pay_forwards
  resources :events
  resources :thanksletters, only: [:new, :create, :destroy]
  # devise_for :accounts, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # high_voltage
  get '*id' => 'pages#show', as: 'front_page'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_digest :string(255)
#  self_intro      :string(255)
#  tw_account      :string(255)
#  fb_account      :string(255)
#  insta_account   :string(255)
#  admin           :boolean          default(FALSE)
#  picture         :string(255)
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
    has_many :thanksletters, dependent: :destroy
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    mount_uploader :picture, PictureUploader
    validates :name, presence: true, length:{maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length:{maximum: 255},
               format: { with: VALID_EMAIL_REGEX },
               uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length:{minimum:6}, allow_nil: true
    validates :self_intro, length:{maximum: 60}

    #fixture向けのdigestメソッド追加
    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def User.new_token
      SecureRandom.urlsafe_base64
    end

    # 永続セッションのためにユーザーをデータベースに記憶する
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

     # 渡されたトークンがダイジェストと一致したらtrueを返す
    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

     # ユーザーのログイン情報を破棄する
    def forget
      update_attribute(:remember_digest, nil)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page:params[:page])
  end

  def show
    @user = User.find(params[:id])
    @receiver_id = Thanksletter.where(receiver_id: @user.id)
    @thanksletters = @receiver_id.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザー登録が完了しました！"
      redirect_to("/users/#{@user.id}")
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end 

  def update  
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save      
      redirect_to @user, notice: "ユーザー情報を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :self_intro, :fb_account, :tw_account, :insta_account, :picture)
  end

  #beforeフィルター

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(@user) unless current_user?(@user)
  end

  # 管理者かどうか確認
  def admin_user
    redirect_to(@user) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

#   # 引数で与えられたユーザーのGravatar画像を返す
#   def gravatar_for(user, size: 80)
#     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
# 　　　size = options[:size]
#     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
#     image_tag(gravatar_url, alt: user.name, class: "gravatar")
#   end
end

app/views/users/_header.slim
.header
    .header-top
      .icon-left
        = image_tag "menu-icon.png", :class => "menu-icon active-icon"
        = image_tag "cancel-icon.png", :class => "cancel-icon"
      .menu-title
        = link_to '/'
         |
        .musubi-logo
          = image_tag 'musubi-logo-type-white.png', :class => "musubi-icon"
      .icon-right
        = image_tag 'message-icon.png', :class => "message-icon"
    .header-menu
      ul.header-menu-list
        / li.header-menu-item UKIUKI残高
        li.header-menu-item プロフィール登録・編集
        / li.header-menu-item 信頼できる仲間をMusubiに招待する
        li.header-menu-item パトロンになる
        li.header-menu-item Musubiの理念
        li.header-menu-item フィードバックを送る
        li.header-menu-item 利用規約
        li.header-menu-item プライバシーポリシー
        / li.header-menu-item よくある質問
        li.header-menu-item Musubiを退会する
    ul.menu-list.header-bottom
      = link_to users_path
        |
        li.menu-item.active-menu-list メンバー
      = link_to events_path
        |
        li.menu-item イベント
      = link_to pay_forwards_path
        |
        li.menu-item みんなの恩贈り
      li.menu-item みんなのサンクスレター
    / .search-box
    /   input type = "text"

app/views/users/edit.html.slim
.edit-user
    h1.form-heading プロフィール編集
.container
  = form_with model: @user, url: user_path, local: true do |f|
    = render 'shared/error_messages', object: f.object 
    .field.field-first
        = f.label :名前, :class => "field-title"
        = f.text_field :name, placeholder: "フルネーム", :class => "name-text"
    .field
        = f.label :画像, :class => "field-title"
        = f.file_field :picture, :class => "picture"
    .field
        = f.label :自己紹介, :class => "field-title"
        = f.text_field :self_intro, placeholder: "60字以内", :class => "self-intro-text"
    .field
        = f.label :Facebookアカウント, :class => "field-title"
        = f.text_field :fb_account, placeholder: "URLを貼ってください", :class => "fb-account-text"
    .field
        = f.label :Twitterアカウント, :class => "field-title"
        = f.text_field :tw_account, placeholder: "URLを貼ってください", :class => "tw-account-text"
    .field
        = f.label :Instagramアカウント, :class => "field-title"
        = f.text_field :insta_account, placeholder: "URLを貼ってください", :class => "insta-account-text"
    .actions = f.submit '編集を保存する'

app/views/users/index.html.slim
.main-menu
  = render 'header'

  = will_paginate
  ul.users
    - @users.each do |user|
        li.user-list
            =link_to user.name, user 
            - if current_user.admin? && !current_user?(user) 
                =link_to "削除", user, method: :delete, data: {confirm: "本当に削除しますか？"}
  = will_paginate


javascript:
   $(".icon-left").click(function(){
      $(".menu-icon").toggleClass("active-icon");
      $(".cancel-icon").toggleClass("active-icon");
      $(".header-menu").slideToggle()
    });
   //クリックしたときのファンクションをまとめて指定
   $('.menu-list li').click(function(){
      //.index()を使いクリックされたタブが何番目かを調べ、
        //indexという変数に代入します。
      var index = $('.menu-list li').index($(this));
      //コンテンツを一度すべて非表示にし、
      // $('.menu-list li').css('display','none');
      //クリックされたタブと同じ順番のコンテンツを表示します。
      // $('.menu-list li').eq(index).css('display','block');
      //一度タブについているクラスselectを消し、
        $('.menu-list li').removeClass('active-menu-list');
        //クリックされたタブのみにクラスselectをつけます。
        $(this).addClass('active-menu-list')
    });

app/views/users/index.slim
.main-menu
  = render 'header'
  ul.users
    - @users.each do |user|
        li.user-list
            =link_to user.name, user
            - if current_user.admin? && !current_user?(user) 
                =link_to "削除", user, method: :delete, data: {confirm: "本当に削除しますか？"}


javascript:
   $(".icon-left").click(function(){
      $(".menu-icon").toggleClass("active-icon");
      $(".cancel-icon").toggleClass("active-icon");
      $(".header-menu").slideToggle()
    });
   //クリックしたときのファンクションをまとめて指定
   $('.menu-list li').click(function(){
      //.index()を使いクリックされたタブが何番目かを調べ、
        //indexという変数に代入します。
      var index = $('.menu-list li').index($(this));
      //コンテンツを一度すべて非表示にし、
      // $('.menu-list li').css('display','none');
      //クリックされたタブと同じ順番のコンテンツを表示します。
      // $('.menu-list li').eq(index).css('display','block');
      //一度タブについているクラスselectを消し、
        $('.menu-list li').removeClass('active-menu-list');
        //クリックされたタブのみにクラスselectをつけます。
        $(this).addClass('active-menu-list')
    });

app/views/users/new.html.slim
.home-bg
      - provide :title, 'Sign up'
      h1.sign-up-title へようこそ
      .sign-up-form
            .row
             .col-md-6#col-md-offset-3
              = form_with model: @user, url: users_path, local: true do |f|
                  = render 'shared/error_messages', object: f.object
                  .field
                  = f.label :画像
                  <br>
                  = f.file_field :picture, class: 'form-control'
                  .field
                  = f.label :名前
                  <br>
                  = f.text_field :name, class: 'form-control'
                  .field
                  = f.label :メールアドレス
                  <br>
                  = f.email_field :email, class: 'form-control'
                  .field
                  = f.label :パスワード
                  <br>
                  = f.password_field :password, class: 'form-control'
                  .field
                  = f.label :password_confirmation, "パスワード確認"
                  <br>
                  = f.password_field :password_confirmation, class: 'form-control'
                  .field
                  = f.submit "作成する", class: "btn btn-primary"
/ 	= image_tag 'musubi-logo-type-white.png', :class => "service-title"
/ 	h1.service-subtitle 感謝で繋がる恩贈りコミュニティ
/ .content
/     = form_with model: @user, url: users_path, local: true do |f|
/         = render 'shared/error_messages'
/         .field
/         = f.label :name
/         = f.text_field :name, class: 'form-control'
/         .field
/         = f.label :email
/         = f.email_field :email, class: 'form-control'
/         .field
/         = f.label :password
/         = f.password_field :password, class: 'form-control'
/         .field
/         = f.label :password_confirmation, "Confirmation"
/         = f.password_field :password_confirmation, class: 'form-control'
/         .field
/          = f.submit "アカウント作成", class: "btn-primary"

app/views/users/show.html.slim
- provide(:title, @user.name)
.row.prof
    .user-info
        - if current_user == @user
            .prof-edit-icon = link_to image_tag("profile-edit-icon.png"), "/users/#{@user.id}/edit"
                / = gravatar_for @user
        div.prof-icon-box
            / = image_tag "/uploads/user/picture/#{@user.id}/#{@user.picture.url}" if @user.picture?
            = image_tag "kao_default.jpg", :class => "prof-icon"
        p.prof-name = @user.name
        .prof-sns
            a.prof-sns-icon.prof-fb> href = "@user.fb_account" Facebook
            a.prof-sns-icon.prof-tw> href = "@user.tw_account" Twitter
            a.prof-sns-icon.prof-insta> href = "@user.insta_account" Instagram
        p.prof-detail-text
            = @user.self_intro
    .container
        ul.prof-list.clearfix
            li.prof-item.active-prof-list サンクスレター
            li.prof-item 恩贈りリスト
            li.prof-item Coming soon
        ul.prof-text-list
            li.prof-text-item
                .content
                       ol.thanksletters
                           = render @thanksletters
                       = will_paginate @thanksletters
                .tag
                    - if current_user != @user
                        = link_to new_thanksletter_path({user_id: @user.id})
                                |
                                button.thanks-letter サンクスレターを贈る
            li.prof-text-item.hide
                ありがとう
            li.prof-text-item.hide
                オリゴ糖


javascript:
 //クリックしたときのファンクション
    $('.prof-list li').click(function(){
        //.index()を使いクリックされたタブが何番目かを調べ、
          //indexという変数に代入します。
        var index = $('.prof-list li').index($(this));
        //コンテンツを一度すべて非表示にし、
        $('.prof-text-list li').css('display','none');
        //クリックされたタブと同じ順番のコンテンツを表示します。
        $('.prof-text-list li').eq(index).css('display','block');
        //一度タブについているクラスactive-prof-listを消し、
        $('.prof-list li').removeClass('active-prof-list');
          //クリックされたタブのみにクラスactive-prof-listをつけます。
        $(this).addClass('active-prof-list')
    });
    //         li.bar-item comming soon
    // .tag
    //     - if current_user != @user
    //         = link_to new_thanksletter_path({user_id: @user.id})
    //             |
    //             button.thanks-letter サンクスレターを贈る