config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index"
  # get "/signup" => "users#new"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  resources :users
  # resources :accounts
  resources :pay_forwards
  resources :events
  resources :thanksletters, only: [:new, :create, :destroy]
  # devise_for :accounts, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # high_voltage
  get '*id' => 'pages#show', as: 'front_page'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  event_date :date
#  place      :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#

class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
        redirect_to @event, notice: 'event was successfully created.'
    else
        render :new
    end
  end
end

app/views/events/index.html.slim
.main-menu
  .header
    .header-top
      .icon-left
        = image_tag "menu-icon.png", :class => "menu-icon active-icon"
        = image_tag "cancel-icon.png", :class => "cancel-icon"
      .menu-title
        = link_to '/'
         |
        .musubi-logo
          = image_tag 'musubi-logo-type-white.png', :class => "musubi-icon"
      .icon-right
        = image_tag 'message-icon.png', :class => "message-icon"
    .header-menu
      ul.header-menu-list
        / li.header-menu-item UKIUKI残高
        li.header-menu-item プロフィール登録・編集
        / li.header-menu-item 信頼できる仲間をMusubiに招待する
        li.header-menu-item パトロンになる
        li.header-menu-item Musubiの理念
        li.header-menu-item フィードバックを送る
        li.header-menu-item 利用規約
        li.header-menu-item プライバシーポリシー
        li.header-menu-item よくある質問
        / li.header-menu-item Musubiを退会する
    ul.menu-list.header-bottom
      = link_to users_path
        |
        li.menu-item メンバー
      = link_to events_path
        |
        li.menu-item.active-menu-list イベント
      = link_to pay_forwards_path
        |
        li.menu-item みんなの恩贈り

      li.menu-item みんなのサンクスレター
    /   .search-box
    /     input type = "text"
  .body
      .content-itemz
        ul
          - @events.each do |ev|
            li
              = link_to event_path(ev)
                h2= ev.title
                p= ev.event_date
                p= ev.place


  = link_to '新しくつくる', new_event_path

javascript:
 $(".icon-left").click(function(){
    $(".menu-icon").toggleClass("active-icon");
    $(".cancel-icon").toggleClass("active-icon");
    $(".header-menu").slideToggle()
  });
 //クリックしたときのファンクションをまとめて指定
 $('.menu-list li').click(function(){
    //.index()を使いクリックされたタブが何番目かを調べ、
      //indexという変数に代入します。
    var index = $('.menu-list li').index($(this));
    //コンテンツを一度すべて非表示にし、
    // $('.menu-list li').css('display','none');
    //クリックされたタブと同じ順番のコンテンツを表示します。
    // $('.menu-list li').eq(index).css('display','block');
    //一度タブについているクラスselectを消し、
      $('.menu-list li').removeClass('active-menu-list');
      //クリックされたタブのみにクラスselectをつけます。
      $(this).addClass('active-menu-list')
  });

app/views/events/new.html.slim
= form_with model: @events, multipart: true, local: true do |f|

  .field
    = f.label :詳細, :class => "field-body"
    = f.text_area :body, placeholder: 'イベントURL', :class => "body-url"
  .actions = f.submit '公開する'