config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index"
  # get "/signup" => "users#new"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  resources :users
  # resources :accounts
  resources :pay_forwards
  resources :events
  resources :thanksletters, only: [:new, :create, :destroy]
  # devise_for :accounts, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # high_voltage
  get '*id' => 'pages#show', as: 'front_page'
end

app/models/pay_forward.rb
# == Schema Information
#
# Table name: pay_forwards
#
#  id         :integer          not null, primary key
#  account_id :integer
#  title      :string(255)
#  body       :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  date       :string(255)
#  place      :string(255)
#  picture    :string(255)
#
# Indexes
#
#  index_pay_forwards_on_account_id  (account_id)
#

class PayForward < ApplicationRecord
  belongs_to :account, optional: true
  mount_uploader :picture, PictureUploader
  has_many :tag_pay_forwards
  has_many :tag, through: :tag_pay_forwards
  has_many :interests
  validate :picture_size

  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/pay_forwards_controller.rb
class PayForwardsController < ApplicationController
  before_action :set_pay_forward, only: %i[show]

  def index
    @pay_forwards = PayForward.all
  end

  def show
    @pay_forward = PayForward.find(params[:id])
    # @image_file_obj = params[:pay_forward][:image_name]
    # params[:pay_forward][:image_name] = @image_file_obj.original_filename
  end

  def new
    @pay_forward = PayForward.new
  end

  def create
    @pay_forward = PayForward.new(pay_forward_params)
    if @pay_forward.save
      redirect_to @pay_forward, notice: '恩送り情報を編集しました'
    else
      render :new
    end
    
  end

  def edit
    @pay_forward = PayForward.find(params[:id])
  end

  def update
    @pay_forward = PayForward.find(params[:id])
    @pay_forward.update_attributes(pay_forward_params)
    if @pay_forward.save
      redirect_to @pay_forward, notice: '恩贈りが'
    else
      render :edit
    end
  end

  private

  def set_pay_forward
    @musubi = PayForward.find(params[:id])
  end


  # createアクションのpay_forward_paramsに入る
  def pay_forward_params
    params.require(:pay_forward).permit(:title, :body, :date, :place, :picture)
  end

end

app/views/pay_forwards/_form.slim
= form_with model: @pay_forward, multipart: true, local: true do |f|
  / .top-image
  /   = f.label :画像, :class => "field-title"
  /   = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', :class => "picture"

  .field.field-first
    = f.label :タイトル, :class => "field-title"
    = f.text_field :title, placeholder: 'タイトル (20字以内)', :class => "title-text"
  .field
    = f.label :日時, :class => "field-title"
    = f.text_field :date, placeholder: '例：1/20, 毎週土曜日, 要相談など', :class => "date-text"
  .field
    = f.label :場所, :class => "field-title"
    = f.text_field :place, placeholder: '地域 (渋谷、新宿、横浜など）', :class => "place-text"
  .field
    = f.label :詳細, :class => "field-title"
    = f.text_area :body, placeholder: '詳細 (200文字以内)', :class => "body-text"
  .actions = f.submit '公開する'

app/views/pay_forwards/_header.slim
.header
    .header-top
      .icon-left
        = image_tag "menu-icon.png", :class => "menu-icon active-icon"
        = image_tag "cancel-icon.png", :class => "cancel-icon"
      .menu-title
        = link_to '/'
         |
        .musubi-logo
          = image_tag 'musubi-logo-type-white.png', :class => "musubi-icon"
      .icon-right
        = image_tag 'message-icon.png', :class => "message-icon"
    .header-menu
      ul.header-menu-list
        / li.header-menu-item UKIUKI残高
        li.header-menu-item プロフィール登録・編集
        / li.header-menu-item 信頼できる仲間をMusubiに招待する
        li.header-menu-item パトロンになる
        li.header-menu-item Musubiの理念
        li.header-menu-item フィードバックを送る
        li.header-menu-item 利用規約
        li.header-menu-item プライバシーポリシー
        / li.header-menu-item よくある質問
        li.header-menu-item Musubiを退会する
    ul.menu-list.header-bottom
      = link_to users_path
        |
        li.menu-item メンバー
      = link_to events_path
        |
        li.menu-item イベント
      = link_to pay_forwards_path
        |
        li.menu-item.active-menu-list みんなの恩贈り
      / li.menu-item みんなのサンクスレター
    / .search-box
    /   input type = "text"

app/views/pay_forwards/edit.html.slim
.edit-pf
	h1.edit-pf-title 恩贈りの情報を編集
.container
   = form_with model: @pay_forward, url: pay_forward_path, local: true do |f|
    / .top-image
    /   =f.label :画像
    /   =form_tag(pay_forwards_path, {multipart: true})
    /   <input name="image" type="file">

    .field.field-first
      = f.label :タイトル, :class => "field-title"
      = f.text_field :title, placeholder: @pay_forward.title, :class => "title-text"
    .field
      = f.label :日時, :class => "field-title"
      = f.text_field :date, placeholder: @pay_forward.date, :class => "date-text"
    .field
      = f.label :場所, :class => "field-title"
      = f.text_field :place, placeholder: @pay_forward.place, :class => "place-text"
    .field
      = f.label :詳細, :class => "field-title"
      = f.text_area :body, placeholder: @pay_forward.body, :class => "body-text"
    .actions = f.submit '編集を保存する'

app/views/pay_forwards/index.html.slim
.main-menu
  = render 'header'
  .content-list
      .content-item
        ul.clearfix
          - @pay_forwards.each do |pf|
            li.item-list
              = link_to pay_forward_path(pf)
                = image_tag "default.png"
                h2.pf-place= pf.place
                h2.pf-title= pf.title
.create-item-btn
  = link_to '恩を贈る', new_pay_forward_path, :class => "create-item"
  = image_tag 'UKIUKI-give.png', :class => "give-icon"

javascript:
   $(".icon-left").click(function(){
      $(".menu-icon").toggleClass("active-icon");
      $(".cancel-icon").toggleClass("active-icon");
      $(".header-menu").slideToggle()
    });
   //クリックしたときのファンクションをまとめて指定
   $('.menu-list li').click(function(){
      //.index()を使いクリックされたタブが何番目かを調べ、
        //indexという変数に代入します。
      var index = $('.menu-list li').index($(this));
      //コンテンツを一度すべて非表示にし、
      // $('.menu-list li').css('display','none');
      //クリックされたタブと同じ順番のコンテンツを表示します。
      // $('.menu-list li').eq(index).css('display','block');
      //一度タブについているクラスselectを消し、
        $('.menu-list li').removeClass('active-menu-list');
        //クリックされたタブのみにクラスselectをつけます。
        $(this).addClass('active-menu-list')
    });

app/views/pay_forwards/new.html.slim
.create-pf
	h1.create-pf-title 恩贈りの情報を入力
	= render 'form'

app/views/pay_forwards/show.html.slim
.pay_forward_icon
	.pf-mv
        = image_tag 'default.png', :class => "pf-img"
		/ = image_tag uploads/pay_forward/picture/
        h1.pf-title= @pay_forward.title
    .pf-body
    	h2.pf-date-title 日時
	    p.pf-date-text= simple_format(@pay_forward.date)
	    h2.pf-place-title 場所
	    p.pf-place-text= simple_format(@pay_forward.place)
	    h2.pf-about-title 恩贈りへの想い
	    p.pf-about-text= simple_format(@pay_forward.body)
	    / h2.pf-thanks-title 恩贈りへのサンクスレター

p= link_to '一覧へ', pay_forwards_path
p= link_to '編集', edit_pay_forward_path